[project]
name = "weather"
version = "0.1.0"
description = "Weather server that is accessible via MC protocol"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.5.0",
]
